name: Deploy to Firebase Hosting on Merge or Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies and Build
        run: npm ci && npm test && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_REACT_BEBF8 }}
          channelId: live
          projectId: simple-react-bebf8

      - name: Get Release Details
        if: github.event_name == 'release'
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"
